version: '3.8'

services:
  node:
    container_name: bonsay_admin
    restart: unless-stopped
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - 3010:3000
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - bonsay
networks:
  bonsay:
    external: true
