version: '3.8'

services:
  node:
    image: stplaton/bonsay-admin
    container_name: bonsay_admin
    restart: always
    tty: true
    networks:
      - bonsay
networks:
  bonsay:
    external: true
